### ISSUE TITLE
CMake find_package for OpenCAL libraries

### ISSUE THREAD

**Issue by donatodambrosio** [OpenCALTeam/opencal#17]
It should be great  if someone could create a cmake **find_package** to find and load settings from the different OpenCAL libraries:
- find_package(OpenCAL-1.0  REQUIRED)
- find_package(OpenCAL-OMP-1.0  REQUIRED)
- find_package(OpenCAL-CL-1.0  REQUIRED)
- find_package(OpenCAL-GL-1.0  REQUIRED)

**Comment by knotman90** [comment]
Cmake module for the serial version provided. Basic tests performed. It searches in system paths (`/usr/local/`  etc.) or uses a provided `OPENCAL_HOME` cmake variable as root search path for lib and includes.
Uses `OPENCAL_DEBUG` to output informations about search paths used during cmake path discovery
`cmake -DOPENCAL_DEBUG=ON -DOPENCAL_HOME=/usr/local/`
see commit daaeedc1eded8a74caf47dfdbd3223f6c9cd8673

Issue **not closed** because tests are required, other FindOpenCAL need to be released, and made windows/apple ready.
